# Generated by Django 3.2 on 2021-05-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('location', models.CharField(max_length=100, verbose_name='监控点')),
                ('status', models.CharField(max_length=100, verbose_name='设备状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在用')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备分类')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序')),
            ],
            options={
                'verbose_name': '设备分类',
                'verbose_name_plural': '设备分类',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
            ],
            options={
                'verbose_name': '环境指标',
                'verbose_name_plural': '环境指标',
            },
        ),
        migrations.CreateModel(
            name='GreenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='大棚名称')),
            ],
            options={
                'verbose_name': '大棚列表',
                'verbose_name_plural': '大棚列表',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='监测值')),
                ('create_time', models.DateTimeField(verbose_name='记录时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.device', verbose_name='设备名称')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.environmentindicator', verbose_name='环境指标')),
            ],
            options={
                'verbose_name': '环境数据',
                'verbose_name_plural': '环境数据',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.devicecategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='device',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.greenhouse', verbose_name='大棚'),
        ),
    ]
