# Generated by Django 3.2 on 2021-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontrol',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='指令名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thresholdcontrol',
            name='name',
            field=models.CharField(default='null', max_length=100, verbose_name='指令名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timercontrol',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='指令名称'),
            preserve_default=False,
        ),
    ]
