# Generated by Django 3.2 on 2021-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20210513_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='status',
            field=models.CharField(default='启动', max_length=10, verbose_name='控制状态'),
        ),
        migrations.AlterField(
            model_name='devicecontrol',
            name='control_id',
            field=models.IntegerField(null=True, verbose_name='控制信息'),
        ),
        migrations.AlterField(
            model_name='devicecontrol',
            name='control_type',
            field=models.IntegerField(default=1, verbose_name='控制方式'),
        ),
    ]
