# Generated by Django 3.2 on 2021-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210514_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhistory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='timercontrol',
            name='repeat_type',
            field=models.CharField(default='不重复', max_length=10, verbose_name='重复方式'),
        ),
    ]
