# Generated by Django 3.2 on 2021-05-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        ('controller', '0004_auto_20210514_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdcontrol',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.device', verbose_name='设备名称'),
        ),
    ]
